version: '3'

services:
  pokemon-go:
    container_name: pokemon-go   
    build:
      context: .                
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always            
